---
title: "R Course Outline"
author: "aaron mamula"
date: "2/25/2020"
output: html_document
---

# {.tabset .tabset-fade .tabset-pills}

## About the Course

There is R "the language" and then there is R "the experience." Learning R "the language" is probably just like learning any other programming language and I don't feel qualified to advise anyone on the best way to do that. I program mostly in R and a little in Python, SQL, java, Visual Basic, and C. I don't have any particularly inspiring thoughts on how to learn "R the language." I just kinda started writing code, getting frustrated when it didn't work, changing little things, trying again, and doing that over and over until stuff started working.

To the extent that I have anything valuable to offer you, it's my understanding of R "the experience." By that I mean using the various tools and integrations in the R ecosystem to streamline data analysis.  

That's a long-winded way of saying that this isn't a course on learning R programming. It's a course on learning to use R to do data analysis. Developing some R progamming dexterity will be a natural by-product of the course but it's not the primary focus. 

## Course Design 

I've organized the lessons for this course into two partitions: Skills and Recipes.

Skills are lessons oriented towards *doing* tasks (importing data, cleaning data, visualizing data, etc.).

Recipes are vignettes focused on *making* things.

The dichotomy of *doing* things versus *making* things is certainly not perfect. My hope is that the *Skills* portion provides enough foundational material to get us all comfortable with basic data operations. Then the *Recipes* portion hopefully builds on that foundation by illustrating how the various skills can be folded together to form a reproducable piece of analysis. 

## Logistics {.tabset}

### R Studio

The course will be taught in R Studio. Some things to know about R Studio off-the-bat:

* R Studio is an Integrated Development Enviroment for the R language
* R Studio is not the only way to interface with R...but it is a very popular tool 
* This courses will use a cloud version of R Studio which means that you shouldn't have to install anything on your own machine if you don't want to. You should be able to "run R code" from within the cloud hosted R Studio instance.

### Lesson Organization

Each lesson is a separate project in the R Studio Cloud space, *NMFS-Econ-HD-Workshop*. It is my understanding that, with access to this R Studio Cloud Space, you all should be able to run the code provided in your own environments.

In each individual lesson you will find a file called *START HERE* with the extension ```.Rmd```. 

### GitHub

In addition to their availability within the R Studio Cloud classromm space, all code files and data for the course are available in the following GitHub repository:

https://github.com/aaronmams/operation-minty-hippo

## Skills {.tabset .tabset-fade .tabset-pills}

This Skills portion of the course was developed around a set of data-centric and data-adjacent tasks that I percieve to be ubiquitous among social science researchers. The lessons are as follows (links to individual lessons are provided):

1. [Importing Data](https://github.com/aaronmams/operation-minty-hippo/blob/master/Skills/Skill-1-Data-Import-v.1.Rmd)
2. [Defining Data](https://github.com/aaronmams/operation-minty-hippo/blob/master/Skills/Skill-2-Data-Types-and-Structures.Rmd)
3. [Wrangling Data](https://github.com/aaronmams/operation-minty-hippo/blob/master/Skills/Skill-3-Data-Wrangling.Rmd)
4. [Visualizing Data](https://github.com/aaronmams/operation-minty-hippo/blob/master/Skills/Skill-4-Introductory-Data-Visualization.Rmd)
5. [Data Pipelines](https://github.com/aaronmams/operation-minty-hippo/blob/master/Skills/Skill-5-Advanced-Data-Import-v.1.Rmd) and [Data Streams](https://github.com/aaronmams/operation-minty-hippo/blob/master/Skills/Skill-5-Advanced-Data-Import-v.2.Rmd)
6. [Advanced Data Visualization](https://github.com/aaronmams/operation-minty-hippo/blob/master/Skills/Skill-6-Advanced-Data-Visualization.Rmd)

## Recipes {.tabset}

My hope is that the Recipes section will serve two primary functions:

1. provide some reproducable data analysis of the "approachable-to-mildly-intimidating" variety that can be used to practice skills, and

2. provide some inspiration in the form of polished finished products that showcase interesting things that can be done with R.

### Classic Econ Problems

The Project [Causal Inference with R](https://github.com/aaronmams/operation-minty-hippo/blob/master/Recipes/Recipe-3-Synthetic-Control.Rmd) provides ```.Rmd``` files to conduct the following analysis:

1. Implement the Regression Discontinuity technique 
2. Implement a suit of estimation techniques commonly referenced as part of the Rubin-Neyman Potential Outcome Framework
3. Apply the quasi-experimental technique, Synthetic Control

### Text Mining/Content Analysis

The Project [Mining Twitter for Sentiment Analysis](https://github.com/aaronmams/operation-minty-hippo/blob/master/Recipes/Recipe-4-Text-Mining.Rmd) provides R code used for the following:

1. illustrate how data can be mined from the Twitter API using R
2. Reproduce an analysis of predicting sentiment using Twitter Data and the Naive Bayes predictive model.

### Workflows and Integrations

This is a guest lesson from Geret Depiper from the NEFSC. Geret will provide a "how we built this" lesson looking at the [Summer Flounder model supporting the Mid Atlantic Fishery Management Council's Ecosystem Approach to Fisheries Management](https://gdepiper.github.io/Summer_Flounder_Conceptual_Models/sfconsmod_riskfactors_subplots.html).

The lesson will demonstrate some interesting features of R and GitHub integration:

* R and R Markdown was used to create a dynamic document
* The interactive document was published to the web with GitHub pages to promote stakeholder engagement and invite public comment

### Bio-economics and Functional Programming

This is another place holder for Allen Chen (NWFSC). Allen agreed to do a demo on functional programming, bio-economic modeling, and use of the ```FLR``` Library.

[FLR](https://flr-project.org/) is

>a collection of tools for quantitative fisheries science, developed in the R language, that facilitates the construction of bio-economic simulation models of fisheries systems

### Advanced Visualization

This section will provide the following recipes:

* [Data Rich Maps with sf and Census Data]()
* [More Data Rich Maps with Covid-19 Data]()
* An [R Shiny]() guest lesson with Erin Steiner/Ashley Vizek from NWFSC


### Voting Patterns Analysis

* A "voting" example
    + use Census Bureau API to get congressional district boundaries and some data (data acquisition skills)
    + get election results by congressional district (more data acquisition skills)
    + do some analysis on voting patterns ()

I have some data sets on congressional district spatial boundaries, characteristics, and voting patterns here:

[https://github.com/aaronmams/R-spatial/tree/master/R](https://github.com/aaronmams/R-spatial/tree/master/R)

### Machine Learning

I have a project I presented to our lab's R Workgroup on using the Caret Package to train/test machine learning pipelines. I could totally recycle this...or somebody else could maybe do a machine learning thing.

### Other Ideas

* other API-centric stuff (Google Trends??)
* other cool mapping stuff (I've heard a lot of an R bridge to ArcGIS but I've only really used the simple features package for spatial analysis and mapping stuff)
* any cool bayesian stuff?? I know there is an R Exention of Gelman's STAN but I haven't used it.

### Time Series

https://aaronmams.github.io/State-Space-Models-with-Seasonal-Data/
